In [1]:
import pandas as pd

data = pd.read_csv('/Users/nabraja/Sapient/Projects/Lloyds/MIP/DS/Codebase/mip-python-training/data/flights.csv')

In [2]:
data.shape

(499999, 31)

In [23]:
data.head(100)

,YEAR,MONTH,DAY,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,AS,98,N407AS,ANC,SEA,5,2354.0,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,AA,2336,N3KUAA,LAX,PBI,10,2.0,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,US,840,N171US,SFO,CLT,20,18.0,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,AA,258,N3HYAA,LAX,MIA,20,15.0,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,AS,135,N527AS,SEA,ANC,25,24.0,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,DL,806,N3730B,SFO,MSP,25,20.0,...,610.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,NK,612,N635NK,LAS,MSP,25,19.0,...,509.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,US,2013,N584UW,LAX,CLT,30,44.0,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,AA,1112,N3LAAA,SFO,DFW,30,19.0,...,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,DL,1173,N826DN,LAS,ATL,30,33.0,...,656.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,2015,1,1,DL,2336,N958DN,DEN,ATL,30,24.0,...,453.0,-30.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,AA,1674,N853AA,LAS,MIA,35,27.0,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12,2015,1,1,DL,1434,N547US,LAX,MSP,35,35.0,...,605.0,-4.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
13,2015,1,1,DL,2324,N3751B,SLC,ATL,40,34.0,...,553.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
14,2015,1,1,DL,2440,N651DL,SEA,MSP,40,39.0,...,557.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,2015,1,1,AS,108,N309AS,ANC,SEA,45,41.0,...,455.0,-14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16,2015,1,1,DL,1560,N3743H,ANC,SEA,45,31.0,...,451.0,-24.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
17,2015,1,1,UA,1197,N78448,SFO,IAH,48,42.0,...,619.0,-7.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,2015,1,1,AS,122,N413AS,ANC,PDX,50,46.0,...,507.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
19,2015,1,1,DL,1670,N806DN,PDX,MSP,50,45.0,...,551.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,1,1,NK,520,N525NK,LAS,MCI,55,120.0,...,543.0,6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,2015,1,1,AA,371,N3GXAA,SEA,MIA,100,52.0,...,939.0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
22,2015,1,1,NK,214,N632NK,LAS,DFW,103,102.0,...,529.0,-1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
23,2015,1,1,AA,115,N3CTAA,LAX,MIA,105,103.0,...,839.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
24,2015,1,1,DL,1450,N671DN,LAS,MSP,105,102.0,...,545.0,-23.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
25,2015,1,1,UA,1545,N76517,LAX,IAH,115,112.0,...,607.0,-11.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26,2015,1,1,AS,130,N457AS,FAI,SEA,115,107.0,...,545.0,-3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
27,2015,1,1,NK,597,N528NK,MSP,FLL,115,127.0,...,607.0,25.0,0,0,NaN,25.0,0.0,0.0,0.0,0.0
28,2015,1,1,US,413,N571UW,LAS,CLT,120,110.0,...,754.0,-31.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
29,2015,1,1,AA,2392,N3HRAA,DEN,MIA,120,141.0,...,709.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2015,1,1,AA,1057,N3ASAA,DFW,MIA,515,703.0,...,1038.0,102.0,0,0,NaN,0.0,0.0,0.0,0.0,102.0
71,2015,1,1,AA,2454,N3ETAA,BOS,MIA,515,510.0,...,845.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
72,2015,1,1,EV,4354,N12142,MKE,IAH,515,517.0,...,826.0,13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
73,2015,1,1,US,425,N174US,PDX,PHX,520,620.0,...,950.0,60.0,0,0,NaN,0.0,0.0,60.0,0.0,0.0
74,2015,1,1,AA,89,N3KVAA,IAH,MIA,520,618.0,...,935.0,54.0,0,0,NaN,0.0,0.0,54.0,0.0,0.0
75,2015,1,1,DL,2099,N355NW,BNA,DTW,520,511.0,...,757.0,-6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
76,2015,1,1,EV,4685,N26545,BRO,IAH,520,517.0,...,629.0,-5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
77,2015,1,1,EV,5583,N882AS,VPS,ATL,520,514.0,...,711.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
78,2015,1,1,OO,5484,N824AS,BOI,SFO,520,525.0,...,615.0,3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
79,2015,1,1,OO,7370,N432SW,BJI,MSP,520,517.0,...,629.0,9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
80,2015,1,1,HA,103,N477HA,HNL,LIH,523,513.0,...,548.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
81,2015,1,1,EV,5187,N720EV,BNA,ATL,525,525.0,...,735.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
82,2015,1,1,MQ,2859,N660MQ,SGF,DFW,525,NaN,...,NaN,NaN,0,1,B,NaN,NaN,NaN,NaN,NaN
83,2015,1,1,UA,1201,N79521,PHL,IAH,530,532.0,...,826.0,6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
84,2015,1,1,UA,1221,N37281,PDX,DEN,530,534.0,...,856.0,4.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
85,2015,1,1,UA,1607,N36476,SEA,DEN,530,529.0,...,906.0,-1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
86,2015,1,1,AA,328,N4XKAA,DEN,DFW,530,623.0,...,941.0,66.0,0,0,NaN,13.0,0.0,53.0,0.0,0.0
87,2015,1,1,EV,5764,N832AS,SBN,ORD,530,527.0,...,511.0,-14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
88,2015,1,1,F9,1279,N918FR,PHL,MCO,530,526.0,...,752.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
89,2015,1,1,NK,409,N509NK,ORD,FLL,530,526.0,...,913.0,-25.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
90,2015,1,1,OO,5460,N583SW,RDD,SFO,530,NaN,...,NaN,NaN,0,1,A,NaN,NaN,NaN,NaN,NaN
91,2015,1,1,OO,6391,N593ML,EUG,DEN,530,526.0,...,926.0,13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
92,2015,1,1,UA,1532,N77066,SFO,DEN,531,550.0,...,923.0,26.0,0,0,NaN,7.0,0.0,19.0,0.0,0.0
93,2015,1,1,UA,1167,N66837,ORD,DEN,533,540.0,...,723.0,3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
94,2015,1,1,UA,1012,N17245,IAD,IAH,535,541.0,...,816.0,14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
95,2015,1,1,B6,2001,N358JB,BUF,JFK,535,530.0,...,648.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
96,2015,1,1,B6,2807,N190JB,PWM,JFK,535,528.0,...,635.0,-25.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
97,2015,1,1,B6,2023,N324JB,JFK,SJU,535,618.0,...,1039.0,19.0,0,0,NaN,0.0,0.0,19.0,0.0,0.0
98,2015,1,1,EV,4557,N12967,CRP,IAH,535,523.0,...,615.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
99,2015,1,1,EV,5241,N849AS,PIA,DTW,535,530.0,...,745.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [5]:
data = data.drop("DAY_OF_WEEK", axis=1)

In [6]:
data = data.rename(columns={"WHEELS_OFF": "HAS_WHEELS"})

In [7]:
data.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
HAS_WHEELS             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [8]:
import numpy as np

chunks = np.array_split(data, 4)

In [9]:
len(chunks)

4

In [10]:
data.describe()

,YEAR,MONTH,DAY,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,HAS_WHEELS,SCHEDULED_TIME,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,499999.0,499999.000000,499999.000000,499999.000000,499999.000000,483583.000000,483583.000000,483295.000000,483295.000000,499998.000000,...,499999.000000,482840.000000,482051.000000,499999.000000,499999.000000,102299.000000,102299.000000,102299.000000,102299.000000,102299.000000
mean,2015.0,1.060062,14.995448,2263.471527,1323.041714,1332.958619,10.122676,16.487882,1356.719161,140.254811,...,1506.507117,1493.392088,6.229602,0.002248,0.033648,13.476202,0.067635,17.999814,22.902130,3.321225
std,0.0,0.237602,9.320105,1803.531063,468.226070,479.872733,37.720260,9.671999,479.845899,74.854061,...,483.437265,503.046868,40.494675,0.047360,0.180322,25.461451,2.027208,45.863346,41.711079,21.899448
min,2015.0,1.000000,1.000000,1.000000,5.000000,1.000000,-48.000000,1.000000,1.000000,23.000000,...,1.000000,1.000000,-82.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.0,1.000000,7.000000,759.000000,925.000000,930.000000,-5.000000,11.000000,946.000000,85.000000,...,1124.000000,1117.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2015.0,1.000000,15.000000,1732.000000,1320.000000,1328.000000,-1.000000,14.000000,1342.000000,122.000000,...,1525.000000,1522.000000,-4.000000,0.000000,0.000000,4.000000,0.000000,2.000000,4.000000,0.000000
75%,2015.0,1.000000,23.000000,3484.000000,1720.000000,1729.000000,9.000000,19.000000,1742.000000,173.000000,...,1914.000000,1915.000000,10.000000,0.000000,0.000000,18.000000,0.000000,18.000000,29.000000,0.000000
max,2015.0,2.000000,31.000000,9793.000000,2359.000000,2400.000000,1988.000000,177.000000,2400.000000,718.000000,...,2359.000000,2400.000000,1971.000000,1.000000,1.000000,830.000000,241.000000,1971.000000,948.000000,1116.000000

In [11]:
std = data["DEPARTURE_DELAY"].std()

In [12]:
third_std = 3 * std
print(third_std)

113.16078076479788

In [13]:
data[((data["DEPARTURE_DELAY"] - data["DEPARTURE_DELAY"].mean())/data["DEPARTURE_DELAY"].std()).abs() < 3]
data["DEPARTURE_DELAY"].head(10)

0   -11.0
1    -8.0
2    -2.0
3    -5.0
4    -1.0
5    -5.0
6    -6.0
7    14.0
8   -11.0
9     3.0
Name: DEPARTURE_DELAY, dtype: float64

In [14]:
data["DEPARTURE_DELAY"].std()

37.720260254932626

In [19]:
delay_airline = data[['AIRLINE', 'DEPARTURE_DELAY']].groupby('AIRLINE').mean()
print(delay_airline)

         DEPARTURE_DELAY
AIRLINE
AA             10.643729
AS              3.430815
B6             10.774558
DL              6.775430
EV             10.043026
F9             19.664576
HA              1.109583
MQ             16.141276
NK             14.016792
OO             12.458124
UA             14.169355
US              6.108520
VX              6.815032
WN              9.631559

In [37]:
morning_flights = data[data["DEPARTURE_TIME"] < 1200].groupby('AIRLINE')

<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x1140fc278>